### ISSUE TITLE
The application crashes when using NewClasses or ModifyClasses on Unity versions below 212 with BNM version 1.2

### ISSUE THREAD

**Issue by solomode0001** [ByNameModding/BNM-Android#18]
Game tested using NewClasses or ModifyClasses with BNM version 1.2:

| Game | Unity Version | Result |
|---|---|---|
| Dead Target | 2021.3.9f1 | Working |
| Stick War: Legacy | 2020.3.47f1 | Crash |
| Dead Trigger | 2019.4.38f1 | Crash |

how to fix this sir @BNM-Dev

**Comment by BNM-Dev** [comment]
For now I can't provide any fix. I don't know why but there is one strange crash appearing when using NewClasses or ModifyClasses. Maybe due to some sneaky memory leak, or other threads related thing. I trying to find it, but no results for now.

**Comment by solomode0001** [comment]
Yes, I have tested it with BNM version 1.3 and it worked for NewClasses, but ModifyClasses still crashes on Unity versions below 2021 while Versions 2021 and above work fine. I hope you will fix this for ModifyClasses in the future. Please take care of your health, and thank you for your hard work on this project.

Game Tested | Unity Version | NewClasses | NewClasses | arm64-v8a | armeabi-v7a
------- | -------- | -------- | -------- | -------- | --------
Aku Si Juragan Empang | 2022.3.2f1 | Working | Working | Working | Working
Dead Target | 2021.3.9f1 | Working | Working | Working | Working
Stick War: Legacy | 2020.3.47f1 | Crash | Working | Working | Working
Dead Trigger | 2019.4.38f1 | Crash | Working | Working | Working

**Comment by solomode0001** [comment]
Yes, I have tested it with BNM version 1.3 and it worked for NewClasses, but ModifyClasses still crashes on Unity versions below 2021 while Versions 2021 and above work fine. I hope you will fix this for ModifyClasses in the future. Please take care of your health, and thank you for your hard work on this project.

Game Tested | Unity Version | NewClasses | NewClasses | arm64-v8a | armeabi-v7a
------- | -------- | -------- | -------- | -------- | --------
Aku Si Juragan Empang | 2022.3.2f1 | Working | Working | Working | Working
Dead Target | 2021.3.9f1 | Working | Working | Working | Working
Stick War: Legacy | 2020.3.47f1 | Crash | Working | Working | Working
Dead Trigger | 2019.4.38f1 | Crash | Working | Working | Working

**Comment by solomode0001** [comment]
Yes, I have tested it with BNM version 1.3 and it worked for NewClasses, but ModifyClasses still crashes on Unity versions below 2021 while Versions 2021 and above work fine. I hope you will fix this for ModifyClasses in the future. Please take care of your health, and thank you for your hard work on this project.

Game Tested | Unity Version | NewClasses | NewClasses | arm64-v8a | armeabi-v7a
------- | -------- | -------- | -------- | -------- | --------
Aku Si Juragan Empang | 2022.3.2f1 | Working | Working | Working | Working
Dead Target | 2021.3.9f1 | Working | Working | Working | Working
Stick War: Legacy | 2020.3.47f1 | Crash | Working | Working | Working
Dead Trigger | 2019.4.38f1 | Crash | Working | Working | Working

**Comment by BNM-Dev** [comment]
Can you provide crash logs?

**Comment by solomode0001** [comment]
The application crashes when using ModifyClasses while NewClasses works fine. The crash occurs when the class is called or loaded, or in my case, it crashes when entering the game when the player spawns

```
[SetupBNM] il2cpp::vm::Class::Init in lib: 0x556604.
[SetupBNM] code has il2cpp_image_get_class. BNM will use it.
[SetupBNM] il2cpp::vm::Class::FromIl2CppType in lib: 0x5588a4.
[SetupBNM] il2cpp::vm::Type::GetClassOrElementClass in lib: 0x571f1c.
[SetupBNM] il2cpp::vm::Image::FromName in lib: 0x55bdcc.
[SetupBNM] il2cpp::vm::Assembly::GetAllAssemblies using domain in lib: 0x556728.
Method: [System.Reflection]::[RuntimeMethodInfo].[MakeGenericMethod_impl], -1 - not found.
[InitNewClasses] Added new class (0x7fb8836f5180) [ModMenu]::[NewClassTest], parent is - [UnityEngine]::[MonoBehaviour], to [Assembly-CSharp.dll].
[ModifyClasses] Added method Update 0 to [Assembly-CSharp.dll]::[]::[AgentHuman].
[ModifyClasses] Class [Assembly-CSharp.dll]::[]::[AgentHuman] successfully changed.


### ### ### ### ### ### ### ### ### ### ### ### ###
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Version '2019.4.40f1 (ffc62b691db5)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'arm64-v8a'
Build fingerprint: 'OPPO/OPPO/PCRT00:9/mv-dev103041042:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2023-11-30 22:23:35+0800
pid: 2704, tid: 2747, name: UnityMain  >>> com.madfingergames.deadtrigger <<<
uid: 10059
signal 11 (SIGSEGV), code 128 (SI_KERNEL), fault addr 0x0
    x0  00007fb88a276e70  x1  0000000000000000  x2  0000000000000060  x3  00007fb88a276e70
    x4  0000000000000000  x5  00007fb8007fb1c0  x6  0000000007b6f650  x7  0000000000000000
    x8  000000000563933c  x9  00007fb7b8ff48b0  x10 00007fb800f08e70  x11 0000000000000000
    x12 00007fb8202f2910  x13 00007fb8202ea650  x14 00007fb800f08d00  x15 00007fb8001a4590
    x16 0000000000000038  x17 00007fb8015e2368  x18 0000000000000001  x19 00007fb88a276f40
    x20 00007fb7b8ff48c0  x21 00007fb884393e40  x22 00007fb88a276e10  x23 0000000000000000
    x24 0000000000000000  x25 0000000000000000  x26 0000000000000000  x27 0000000000000000
    x28 0000000000000000  x29 0000000000000000
    sp  00007fb88a276d80  lr  000000000740c844  pc  0000000005639344

backtrace:
      #00 pc 0000000000535344  /data/app/com.madfingergames.deadtrigger-f5scUvFzWwED4yaOHoF7eg==/lib/arm64/libil2cpp.so (il2cpp_runtime_invoke+8) (BuildId: 9a6f669c41c23ae406759297ea367eb96ce30832)
      #01 pc 0000000000308840  /data/app/com.madfingergames.deadtrigger-f5scUvFzWwED4yaOHoF7eg==/lib/arm64/libunity.so (BuildId: 62c2b1208b408451a693362dab13ae287568fc7d)
      #02 pc 000000000030c1ec  /data/app/com.madfingergames.deadtrigger-f5scUvFzWwED4yaOHoF7eg==/lib/arm64/libunity.so (BuildId: 62c2b1208b408451a693362dab13ae287568fc7d)
      #03 pc 000000000031f6e4  /data/app/com.madfingergames.deadtrigger-f5scUvFzWwED4yaOHoF7eg==/lib/arm64/libunity.so (BuildId: 62c2b1208b408451a693362dab13ae287568fc7d)
      #04 pc 00000000001e62c0  /data/app/com.madfingergames.deadtrigger-f5scUvFzWwED4yaOHoF7eg==/lib/arm64/libunity.so (BuildId: 62c2b1208b408451a693362dab13ae287568fc7d)
      #05 pc 000000000027a7b0  /data/app/com.madfingergames.deadtrigger-f5scUvFzWwED4yaOHoF7eg==/lib/arm64/libunity.so (BuildId: 62c2b1208b408451a693362dab13ae287568fc7d)
      #06 pc 000000000027a7e4  /data/app/com.madfingergames.deadtrigger-f5scUvFzWwED4yaOHoF7eg==/lib/arm64/libunity.so (BuildId: 62c2b1208b408451a693362dab13ae287568fc7d)
      #07 pc 000000000027aa28  /data/app/com.madfingergames.deadtrigger-f5scUvFzWwED4yaOHoF7eg==/lib/arm64/libunity.so (BuildId: 62c2b1208b408451a693362dab13ae287568fc7d)
      #08 pc 00000000003814a4  /data/app/com.madfingergames.deadtrigger-f5scUvFzWwED4yaOHoF7eg==/lib/arm64/libunity.so (BuildId: 62c2b1208b408451a693362dab13ae287568fc7d)
      #09 pc 0000000000394f54  /data/app/com.madfingergames.deadtrigger-f5scUvFzWwED4yaOHoF7eg==/lib/arm64/libunity.so (BuildId: 62c2b1208b408451a693362dab13ae287568fc7d)
      #10 pc 000000000010535c  /system/lib64/arm64/nb/libtcb.so
Background concurrent copying GC freed 28519(2MB) AllocSpace objects, 43(4MB) LOS objects, 50% free, 10MB/21MB, paused 52us total 114.356ms
Tombstone written to: /storage/emulated/0/Android/data/com.madfingergames.deadtrigger/files/tombstone_01
FATAL EXCEPTION: UnityMain
Process: com.madfingergames.deadtrigger, PID: 2704
java.lang.Error: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Version '2019.4.40f1 (ffc62b691db5)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'arm64-v8a'
Build fingerprint: 'OPPO/OPPO/PCRT00:9/mv-dev103041042:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2023-11-30 22:23:35+0800
pid: 2704, tid: 2747, name: UnityMain  >>> com.madfingergames.deadtrigger <<<
uid: 10059
signal 11 (SIGSEGV), code 128 (SI_KERNEL), fault addr 0x0
    x0  00007fb88a276e70  x1  0000000000000000  x2  0000000000000060  x3  00007fb88a276e70
    x4  0000000000000000  x5  00007fb8007fb1c0  x6  0000000007b6f650  x7  0000000000000000
    x8  000000000563933c  x9  00007fb7b8ff48b0  x10 00007fb800f08e70  x11 0000000000000000
    x12 00007fb8202f2910  x13 00007fb8202ea650  x14 00007fb800f08d00  x15 00007fb8001a4590
    x16 0000000000000038  x17 00007fb8015e2368  x18 0000000000000001  x19 00007fb88a276f40
    x20 00007fb7b8ff48c0  x21 00007fb884393e40  x22 00007fb88a276e10  x23 0000000000000000
    x24 0000000000000000  x25 0000000000000000  x26 0000000000000000  x27 0000000000000000
    x28 0000000000000000  x29 0000000000000000
    sp  00007fb88a276d80  lr  000000000740c844  pc  0000000005639344

backtrace:
      #00 pc 0000000000535344  /data/app/com.madfingergames.deadtrigger-f5scUvFzWwED4yaOHoF7eg==/lib/arm64/libil2cpp.so (il2cpp_runtime_invoke+8) (BuildId: 9a6f669c41c23ae406759297ea367eb96ce30832)
      #01 pc 0000000000308840  /data/app/com.madfingergames.deadtrigger-f5scUvFzWwED4yaOHoF7eg==/lib/arm64/libunity.so (BuildId: 62c2b1208b408451a693362dab13ae287568fc7d)
      #02 pc 000000000030c1ec  /data/app/com.madfingergames.deadtrigger-f5scUvFzWwED4yaOHoF7eg==/lib/arm64/libunity.so (BuildId: 62c2b1208b408451a693362dab13ae287568fc7d)
      #03 pc 000000000031f6e4  /data/app/com.madfingergames.deadtrigger-f5scUvFzWwED4yaOHoF7eg==/lib/arm64/libunity.so (BuildId: 62c2b1208b408451a693362dab13ae287568fc7d)
      #04 pc 00000000001e62c0  /data/app/com.madfingergames.deadtrigger-f5scUvFzWwED4yaOHoF7eg==/lib/arm64/libunity.so (BuildId: 62c2b1208b408451a693362dab13ae287568fc7d)
      #05 pc 000000000027a7b0  /data/app/com.madfingergames.deadtrigger-f5scUvFzWwED4yaOHoF7eg==/lib/arm64/libunity.so (BuildId: 62c2b1208b408451a693362dab13ae287568fc7d)
      #06 pc 000000000027a7e4  /data/app/com.madfingergames.deadtrigger-f5scUvFzWwED4yaOHoF7eg==/lib/arm64/libunity.so (BuildId: 62c2b1208b408451a693362dab13ae287568fc7d)
      #07 pc 000000000027aa28  /data/app/com.madfingergames.deadtrigger-f5scUvFzWwED4yaOHoF7eg==/lib/arm64/libunity.so (BuildId: 62c2b1208b408451a693362dab13ae287568fc7d)
      #08 pc 00000000003814a4  /data/app/com.madfingergames.deadtrigger-f5scUvFzWwED4yaOHoF7eg==/lib/arm64/libunity.so (BuildId: 62c2b1208b408451a693362dab13ae287568fc7d)
      #09 pc 0000000000394f54  /data/app/com.madfingergames.deadtrigger-f5scUvFzWwED4yaOHoF7eg==/lib/arm64/libunity.so (BuildId: 62c2b1208b408451a693362dab13ae287568fc7d)
      #10 pc 000000000010535c  /system/lib64/arm64/nb/libtcb.so

	at libil2cpp.il2cpp_runtime_invoke(il2cpp_runtime_invoke:8)
	at libunity.0x308840(Native Method)
	at libunity.0x30c1ec(Native Method)
	at libunity.0x31f6e4(Native Method)
	at libunity.0x1e62c0(Native Method)
	at libunity.0x27a7b0(Native Method)
	at libunity.0x27a7e4(Native Method)
	at libunity.0x27aa28(Native Method)
	at libunity.0x3814a4(Native Method)
	at libunity.0x394f54(Native Method)
	at libtcb.0x10535c(Native Method)


[tombstone_00.txt](https://github.com/ByNameModding/BNM-Android/files/13514302/tombstone_00.txt)

**Comment by BNM-Dev** [comment]
I will add this fix to v1.4 and will fix `Method: [System.Reflection]::[RuntimeMethodInfo].[MakeGenericMethod_impl], -1 - not found.`

**Comment by BNM-Dev** [comment]
I amended commit, try it.

**Comment by solomode0001** [comment]
Congratulations, you have nailed it! You have resolved all the problems and this is the best version of BNM yet. I can’t wait to see more new features that are amazing and thrilling. Stay healthy and thank you very much for your dedication to this project. Kudos to **BYNAMEMODDING!** 😊
