### ISSUE TITLE
Crash at AmongUs

### ISSUE THREAD

**Issue by TomieAi** [ByNameModding/BNM-Android#5]
at TWD and RAID SHADOW LEGENDS it works fine but on AmongUs it just crash I even set the proper settings.
you dont even have to do anything yet to trigger the error.. just include it on cmakelists.txt thats it and it will crash game wont open.

![image](https://user-images.githubusercontent.com/111332073/227586491-9f13032e-93b2-4a2b-b44b-a4e18b6b219a.png)

```shell
03-25 20:51:24.959  5049  5075 E CRASH   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
03-25 20:51:24.959  5049  5075 E CRASH   : Version '2020.3.22f1 (e1a7f79fd887)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'armeabi-v7a'
03-25 20:51:24.959  5049  5075 E CRASH   : Build fingerprint: 'samsung/z3qksx/z3qksx:9/PPR1.180720.122/6736742:user/release-keys'
03-25 20:51:24.959  5049  5075 E CRASH   : Revision: '0'
03-25 20:51:24.959  5049  5075 E CRASH   : ABI: 'arm'
03-25 20:51:24.960  5049  5075 E CRASH   : Timestamp: 2023-03-25 20:51:24+0800      
03-25 20:51:24.960  5049  5075 E CRASH   : pid: 5049, tid: 5075, name: UnityMain  >>> com.innersloth.spacemafia <<<
03-25 20:51:24.960  5049  5075 E CRASH   : uid: 10082
03-25 20:51:24.960  5049  5075 E CRASH   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x6
03-25 20:51:24.960  5049  5075 E CRASH   : Cause: null pointer dereference
03-25 20:51:24.961  5049  5075 E CRASH   :     r0  00000006  r1  e9001f60  r2  00000003  r3  00000000
03-25 20:51:24.961  5049  5075 E CRASH   :     r4  e9002f78  r5  00000006  r6  e8ffbfe0  r7  e9001f60
03-25 20:51:24.961  5049  5075 E CRASH   :     r8  00000006  r9  f2c6ed9c  r10 ca1fefa0  r11 ca1fe590
03-25 20:51:24.961  5049  5075 E CRASH   :     ip  00000002  sp  ca1fe560  lr  0796a90c  pc  0b7ef894
03-25 20:51:24.961  5049  5075 E CRASH   :
03-25 20:51:24.961  5049  5075 E CRASH   : backtrace:
03-25 20:51:24.962  5049  5075 E CRASH   :       #00 pc 0001b894  /system/lib/arm/nb/libc.so (strlen+36) (BuildId: f1478175a6e1d79b85bd0f9edf43ead1)
03-25 20:51:24.962  5049  5075 E CRASH   :       #01 pc 00696908  /data/app/com.innersloth.spacemafia-QQBDcg3gjTMxFew6UL1vlg==/lib/arm/libil2cpp.so (BuildId: 3d9623f6dd6025e28ffad5e8933cb29b979cbad2)
03-25 20:51:24.962  5049  5075 E CRASH   :       #02 pc 0067f08c  /data/app/com.innersloth.spacemafia-QQBDcg3gjTMxFew6UL1vlg==/lib/arm/libil2cpp.so (BuildId: 3d9623f6dd6025e28ffad5e8933cb29b979cbad2)
03-25 20:51:24.963  5049  5075 E CRASH   :       #03 pc 00653a5c  /data/app/com.innersloth.spacemafia-QQBDcg3gjTMxFew6UL1vlg==/lib/arm/libil2cpp.so (il2cpp_init+32) (BuildId: 3d9623f6dd6025e28ffad5e8933cb29b979cbad2)
03-25 20:51:24.963  5049  5075 E CRASH   :       #04 pc 002247e1  /data/app/com.innersloth.spacemafia-QQBDcg3gjTMxFew6UL1vlg==/lib/arm/libunity.so (BuildId: 88606acb4b5775557e8641b5e649f467101a6ded)
03-25 20:51:24.964  5049  5075 E CRASH   :       #05 pc 00270855  /data/app/com.innersloth.spacemafia-QQBDcg3gjTMxFew6UL1vlg==/lib/arm/libunity.so (BuildId: 88606acb4b5775557e8641b5e649f467101a6ded)
03-25 20:51:24.964  5049  5075 E CRASH   :       #06 pc 00271461  /data/app/com.innersloth.spacemafia-QQBDcg3gjTMxFew6UL1vlg==/lib/arm/libunity.so (BuildId: 88606acb4b5775557e8641b5e649f467101a6ded)
03-25 20:51:24.964  5049  5075 E CRASH   :       #07 pc 00280ae1  /data/app/com.innersloth.spacemafia-QQBDcg3gjTMxFew6UL1vlg==/lib/arm/libunity.so (BuildId: 88606acb4b5775557e8641b5e649f467101a6ded)
03-25 20:51:24.964  5049  5075 E CRASH   :       #08 pc 0007e65e  /system/lib/arm/nb/libtcb.so
03-25 20:51:25.125  5049  5075 E CRASH   : Tombstone written to: /storage/emulated/0/Android/data/com.innersloth.spacemafia/files/tombstone_01
03-25 20:51:25.125  5049  5075 E AndroidRuntime: FATAL EXCEPTION: UnityMain
03-25 20:51:25.125  5049  5075 E AndroidRuntime: Process: com.innersloth.spacemafia, PID: 5049
03-25 20:51:25.125  5049  5075 E AndroidRuntime: java.lang.Error: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
03-25 20:51:25.125  5049  5075 E AndroidRuntime: Version '2020.3.22f1 (e1a7f79fd887)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'armeabi-v7a'
03-25 20:51:25.125  5049  5075 E AndroidRuntime: Build fingerprint: 'samsung/z3qksx/z3qksx:9/PPR1.180720.122/6736742:user/release-keys'
03-25 20:51:25.125  5049  5075 E AndroidRuntime: Revision: '0'
03-25 20:51:25.125  5049  5075 E AndroidRuntime: ABI: 'arm'
03-25 20:51:25.125  5049  5075 E AndroidRuntime: Timestamp: 2023-03-25 20:51:24+0800
03-25 20:51:25.125  5049  5075 E AndroidRuntime: pid: 5049, tid: 5075, name: UnityMain  >>> com.innersloth.spacemafia <<<
03-25 20:51:25.125  5049  5075 E AndroidRuntime: uid: 10082
03-25 20:51:25.125  5049  5075 E AndroidRuntime: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x6
03-25 20:51:25.125  5049  5075 E AndroidRuntime: Cause: null pointer dereference    
03-25 20:51:25.125  5049  5075 E AndroidRuntime:     r0  00000006  r1  e9001f60  r2  00000003  r3  00000000
03-25 20:51:25.125  5049  5075 E AndroidRuntime:     r4  e9002f78  r5  00000006  r6  e8ffbfe0  r7  e9001f60
03-25 20:51:25.125  5049  5075 E AndroidRuntime:     r8  00000006  r9  f2c6ed9c  r10 ca1fefa0  r11 ca1fe590
03-25 20:51:25.125  5049  5075 E AndroidRuntime:     ip  00000002  sp  ca1fe560  lr  0796a90c  pc  0b7ef894
03-25 20:51:25.125  5049  5075 E AndroidRuntime:
03-25 20:51:25.125  5049  5075 E AndroidRuntime: backtrace:
03-25 20:51:25.125  5049  5075 E AndroidRuntime:       #00 pc 0001b894  /system/lib/arm/nb/libc.so (strlen+36) (BuildId: f1478175a6e1d79b85bd0f9edf43ead1)
03-25 20:51:25.125  5049  5075 E AndroidRuntime:       #01 pc 00696908  /data/app/com.innersloth.spacemafia-QQBDcg3gjTMxFew6UL1vlg==/lib/arm/libil2cpp.so (BuildId: 3d9623f6dd6025e28ffad5e8933cb29b979cbad2)
03-25 20:51:25.125  5049  5075 E AndroidRuntime:       #02 pc 0067f08c  /data/app/com.innersloth.spacemafia-QQBDcg3gjTMxFew6UL1vlg==/lib/arm/libil2cpp.so (BuildId: 3d9623f6dd6025e28ffad5e8933cb29b979cbad2)
03-25 20:51:25.125  5049  5075 E AndroidRuntime:       #03 pc 00653a5c  /data/app/com.innersloth.spacemafia-QQBDcg3gjTMxFew6UL1vlg==/lib/arm/libil2cpp.so (il2cpp_init+32) (BuildId: 3d9623f6dd6025e28ffad5e8933cb29b979cbad2)
03-25 20:51:25.125  5049  5075 E AndroidRuntime:       #04 pc 002247e1  /data/app/com.innersloth.spacemafia-QQBDcg3gjTMxFew6UL1vlg==/lib/arm/libunity.so (BuildId: 88606acb4b5775557e8641b5e649f467101a6ded)
03-25 20:51:25.125  5049  5075 E AndroidRuntime:       #05 pc 00270855  /data/app/com.innersloth.spacemafia-QQBDcg3gjTMxFew6UL1vlg==/lib/arm/libunity.so (BuildId: 88606acb4b5775557e8641b5e649f467101a6ded)
03-25 20:51:25.125  5049  5075 E AndroidRuntime:       #06 pc 00271461  /data/app/com.innersloth.spacemafia-QQBDcg3gjTMxFew6UL1vlg==/lib/arm/libunity.so (BuildId: 88606acb4b5775557e8641b5e649f467101a6ded)
03-25 20:51:25.125  5049  5075 E AndroidRuntime:       #07 pc 00280ae1  /data/app/com.innersloth.spacemafia-QQBDcg3gjTMxFew6UL1vlg==/lib/arm/libunity.so (BuildId: 88606acb4b5775557e8641b5e649f467101a6ded)
03-25 20:51:25.125  5049  5075 E AndroidRuntime:       #08 pc 0007e65e  /system/lib/arm/nb/libtcb.so
03-25 20:51:25.125  5049  5075 E AndroidRuntime:
03-25 20:51:25.125  5049  5075 E AndroidRuntime:        at libc.strlen(strlen:36)   
03-25 20:51:25.125  5049  5075 E AndroidRuntime:        at libil2cpp.0x696908(Native Method)
03-25 20:51:25.125  5049  5075 E AndroidRuntime:        at libil2cpp.0x67f08c(Native Method)
03-25 20:51:25.125  5049  5075 E AndroidRuntime:        at libil2cpp.il2cpp_init(il2cpp_init:32)
03-25 20:51:25.125  5049  5075 E AndroidRuntime:        at libunity.0x2247e1(Native Method)
03-25 20:51:25.125  5049  5075 E AndroidRuntime:        at libunity.0x270855(Native Method)
03-25 20:51:25.125  5049  5075 E AndroidRuntime:        at libunity.0x271461(Native Method)
03-25 20:51:25.125  5049  5075 E AndroidRuntime:        at libunity.0x280ae1(Native Method)
03-25 20:51:25.125  5049  5075 E AndroidRuntime:        at libtcb.0x7e65e(Native Method)
```

The one version that work for me is the ByNameModding at https://github.com/NepMods/Aide-Imgui/tree/master/app/src/main/jni/ByNameModding.

https://user-images.githubusercontent.com/111332073/227589506-12d04289-f997-4848-be27-aea312c09a7f.mp4

I dont think i will go back again on doing some offset xD after I discover your project xD its so hella easy to use <3 xD

something break on span of that old ByNameModding vs new one. i just dont know what xD also that old one doesnt have BNM::Method which is one of the feature i love sadly.

but it looks like it breaks on PrepareBNM part.. where u hook il2cpp_init

**Comment by TomieAi** [comment]
My theory is right xD PrepareBNM  changes borked it.. I fixed it by reverting the change on PrepareBNM.

**Comment by Scriptor-Lover1500** [comment]
@TomieAi Can you share the way how you fixed? I also love to use latest bnm. But it is giving me headaches with force close crashes by just adding in android.mk.
