### ISSUE TITLE
Need Help! for new object

### ISSUE THREAD

**Issue by tomasky** [ByNameModding/BNM-Android#57]
```cpp
 auto adverclass = Class(OBFUSCATE_BNM("UnityEngine"), OBFUSCATE_BNM("AndroidJavaObject"));
   
    Mono::String *cmethod = BNM::CreateMonoString("com.example.Hello");
    Mono::String *carg0 = BNM::CreateMonoString("Hello");
    Mono::Array<Mono::String *> *cargs = Mono::Array<Mono::String *>::Create({carg0});
    adverclass.CreateNewObjectParameters(cmethod, cargs);
```

what is wrong ? , the game report error and exit

**Comment by Lsc0x80** [comment]
logs?

сб, 27 июл. 2024 г., 14:45 tomaswyz ***@***.***>:

**Comment by tomasky** [comment]
19:39:28.886                 AndroidRuntime (602    4191)  E    at libc.abort(abort:160)
19:39:28.886                 AndroidRuntime (602    4191)  E  ┌ at libil2cpp.std::set_unexpected(void (*)())(s
19:39:28.886                 AndroidRuntime (602    4191)  E  └ et_unexpected:0)
19:39:28.886                 AndroidRuntime (602    4191)  E    at libil2cpp.0x41b258(Native Method)
19:39:28.886                 AndroidRuntime (602    4191)  E    at libil2cpp.0x4184e8(Native Method)
19:39:28.886                 AndroidRuntime (602    4191)  E  ┌ at libil2cpp.__cxa_get_exception_ptr(__cxa_get
19:39:28.886                 AndroidRuntime (602    4191)  E  └ _exception_ptr:0)
19:39:28.886                 AndroidRuntime (602    4191)  E    at libil2cpp.0x417b4c(Native Method)
19:39:28.886                 AndroidRuntime (602    4191)  E    at libil2cpp.0x36b59c(Native Method)
19:39:28.886                 AndroidRuntime (602    4191)  E    at libil2cpp.0x3d14ec(Native Method)
19:39:28.886                 AndroidRuntime (602    4191)  E    at libil2cpp.0xa4f624(Native Method)
19:39:28.886                 AndroidRuntime (602    4191)  E  ┌ at libbtcore.BNM::PropertyBase::str() const(st
19:39:28.886                 AndroidRuntime (602    4191)  E  └ r:640)
19:39:28.886                 AndroidRuntime (602    4191)  E    at libbtcore.0x2d75c(Native Method)

**Comment by BNM-Dev** [comment]
Try catch exception using BNM API described in [example 8](https://github.com/ByNameModding/BNM-Android/blob/06729e1a5ce44216931282ee6f4707045c3a4129/examples/08_Exceptions.cpp#L15).

**Comment by tomasky** [comment]
why ?
this is ok.
```cpp
 BNM_try
        adverclass.CreateNewObjectParameters(cmethod, carg0);
    BNM_catch(exception)
    BNM_end_try
```
but this is fail, 
```cpp
 BNM_try
        adverclass.CreateNewObjectParameters(cmethod, cargs);
    BNM_catch(exception)
    BNM_end_try
```

```java 
package com.example;
 public class Hello{
Hello(String[] hello){
}
 Hello(String hello){
}
}
```

**Comment by BNM-Dev** [comment]
> 19:39:28.886 AndroidRuntime (602 4191) E ┌ at libbtcore.BNM::PropertyBase::str() const(st
> 19:39:28.886 AndroidRuntime (602 4191) E └ r:640)

After checking crash log again, I saw this. Crash in some property that you trying to get info about using `str()`. Not in `CreateNewObjectParameters`

**Comment by tomasky** [comment]
thanks , now i have this problem with dobby:

```cpp
    auto gameObject = BNM::Class("UnityEngine", "GameObject").CreateNewObjectParameters();
```
no errors report and the game exit

**Comment by BNM-Dev** [comment]
Only thing that I can recommend, add logs on each line of code. This types of crashes hard to determine.

**Comment by tomasky** [comment]
No error, even if I did just this:
but ,It's okay to create other objects
```cpp
 BNM_try
         auto gameObject = BNM::Class("UnityEngine", "GameObject").CreateNewObjectParameters();
       BNM_catch(exception)
        auto className = exception.ClassName();
        auto message = exception.Message();
        BNM_LOG_WARN("returned exception (in try catch) [%s]: %s", className.c_str(), message.c_str());
    BNM_end_try

```

**Comment by tomasky** [comment]
this is ok:
```cpp
    auto gameObject = BNM::Class("UnityEngine", "Texture").CreateNewObjectParameters();

```

**Comment by tomasky** [comment]
Can you help me test this use case？ ，I have no idea：
just these codes:
```cpp
void onload(){
 BNM_try
         auto gameObject = BNM::Class("UnityEngine", "GameObject").CreateNewObjectParameters();
       BNM_catch(exception)
        auto className = exception.ClassName();
        auto message = exception.Message();
        BNM_LOG_WARN("returned exception (in try catch) [%s]: %s", className.c_str(), message.c_str());
    BNM_end_try
}
```

**Comment by BNM-Dev** [comment]
Where do you call this code? If in method sent to AddOnLoadEvent, it will crash. This event called right after il2cpp vm initialized, not unity. You need hook sth and in it create new GameObject.

**Comment by tomasky** [comment]
in file example/05_ClassesManagement.cpp :
```cpp
#include <BNM/UserSettings/GlobalSettings.hpp>
#include <BNM/Exceptions.hpp>

#include <BNM/ClassesManagement.hpp>
#include <BNM/BasicMonoStructures.hpp>
#include <BNM/UnityStructures.hpp>
#include <BNM/Field.hpp>
#include "BNM/ComplexMonoStructures.hpp"



using namespace BNM::Structures::Unity;
using namespace BNM::Structures::Mono;

struct MyClass : public BNM::UnityEngine::MonoBehaviour {
    BNM_CustomClass(MyClass, BNM::CompileTimeClassBuilder("","MyClass").Build(), BNM::CompileTimeClassBuilder("UnityEngine","MonoBehaviour").Build(), {});

    void Update() {
        BNM_LOG_INFO("Call Update");
    }

    BNM_CustomMethod(Update, false, BNM::GetType<void>(), "Update");
};

BNM::Method<void*> addComponent;
BNM::Method<void> dontDestroyOnLoad;

void *AttachComponent() {
    auto *name = BNM::CreateMonoString("Hello");
    auto gameObject = BNM::Class("UnityEngine", "GameObject").CreateNewObjectParameters(name);
    
    // addComponent[gameObject](MyClass::BNMCustomClass.type);
    dontDestroyOnLoad(gameObject);
    return gameObject;
}

void OnLoaded_Example_05() {
    addComponent = BNM::Class("UnityEngine", "GameObject").GetMethod("AddComponent", {"componentType"});
    dontDestroyOnLoad = BNM::Class("UnityEngine", "Object").GetMethod("DontDestroyOnLoad");

    // auto r = AttachComponent();
}

```

**Comment by BNM-Dev** [comment]
I will fix examples. Now hook sth like OnSceneLoaded or similar. And create object here.

**Comment by tomasky** [comment]
Thank your advice, but now:
```cpp
void (*old_OnSceneLoaded)(BNM::IL2CPP::Il2CppObject *,BNM::IL2CPP::Il2CppObject *,BNM::IL2CPP::Il2CppObject *);
void OnSceneLoaded(BNM::IL2CPP::Il2CppObject *instance,BNM::IL2CPP::Il2CppObject * tps ,BNM::IL2CPP::Il2CppObject *method) {
    BNM_LOG_INFO("gameobject name: \"facebook\"; ");
    
      BNM_try
        old_OnSceneLoaded(instance,tps,method); 
          auto *name = BNM::CreateMonoString("BackPlugin");
        BNM::UnityEngine::Object  *gameObject = (BNM::UnityEngine::Object *)BNM::Class("UnityEngine", "GameObject").CreateNewObjectParameters(name);
    
        BNM::Method<BNM::IL2CPP::Il2CppObject *>  addComponent = BNM::Class("UnityEngine", "GameObject").GetMethod("AddComponent", {"componentType"});
// this line crash ,no error , game exit;
        addComponent[gameObject](MyClass2::BNMCustomClass.type);
    BNM_catch(exception)
        auto className = exception.ClassName();
        auto message = exception.Message();
        BNM_LOG_WARN("returned exception (in try catch) [%s]: %s", className.c_str(), message.c_str());
    BNM_end_try
}
```

**Comment by tomasky** [comment]
thank your help, now All my problems are solved ！

**Comment by gamesky** [comment]
@BNM-Dev  how to hook this?
```c#
    ReturnType _CallStatic(System.String methodName, System.Object[] args);
```

```cpp
    auto javaobj0 = Class(OBFUSCATE_BNM("UnityEngine"), OBFUSCATE_BNM("AndroidJavaObject"));
    BNM::Method<bool> javaclasscall2 = javaobj0.GetMethod(OBFUSCATE_BNM("_CallStatic"),2);
    auto generstaticall = javaclasscall2.GetGeneric({GetType<bool>().ToClass()});
    HOOK(generstaticall, onCallStatic2, old_onCallStatic2);
```
report this:

AndroidJavaObject].(_CallStatic){arguments count:2 } is not generic!

**Comment by tomasky** [comment]
@BNM-Dev  how to hook this?
```c#
    ReturnType _CallStatic(System.String methodName, System.Object[] args);
```

```cpp
    auto javaobj0 = Class(OBFUSCATE_BNM("UnityEngine"), OBFUSCATE_BNM("AndroidJavaObject"));
    BNM::Method<bool> javaclasscall2 = javaobj0.GetMethod(OBFUSCATE_BNM("_CallStatic"),2);
    auto generstaticall = javaclasscall2.GetGeneric({GetType<bool>().ToClass()});
    HOOK(generstaticall, onCallStatic2, old_onCallStatic2);
```
report this:

AndroidJavaObject].(_CallStatic){arguments count:2 } is not generic!

**Comment by BNM-Dev** [comment]
Use `javaobj0.GetMethods(false);` to iterate all methods and find needed generic one. Use `method._data->is_generic` to check.

**Comment by tomasky** [comment]
sorry , back the old problem, how to call this ? 
this doesn't work

```cpp
    System.Void Call(System.String methodName, System.Object[] args); // 0x00a4fa10
     Mono::Array<Mono::String *> *cargs = Mono::Array<Mono::String *>::Create({BNM::CreateMonoString("1")});
      method[instance](BNM::CreateMonoString("backs"),cargs);



```
